# Generated by Django 3.2.9 on 2021-11-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('co', models.FloatField()),
                ('propane', models.FloatField()),
                ('flame', models.IntegerField(max_length=1)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
