# Generated by Django 3.2.9 on 2021-11-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvalue',
            name='flame',
            field=models.IntegerField(),
        ),
    ]
