# Generated by Django 3.2.9 on 2021-11-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211116_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YearStatValue',
        ),
    ]
