# Generated by Django 3.2.9 on 2021-11-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211121_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystatvalue',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='monthstatvalue',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
