# Generated by Django 3.2.10 on 2022-01-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211122_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daystatvalue',
            old_name='propane',
            new_name='lpg',
        ),
        migrations.RenameField(
            model_name='monthstatvalue',
            old_name='propane',
            new_name='lpg',
        ),
        migrations.RenameField(
            model_name='sensorvalue',
            old_name='propane',
            new_name='lpg',
        ),
    ]
